my_string = input("Будете пиво?: ")
print(my_string)
print(len(my_string))
print(my_string.upper())
print(my_string.lower())
my_stringNOspaces = my_string.replace(" ", "")
print(my_stringNOspaces)
print(my_string[0])
print(my_string[-1])